---
become_override: false
ocp_username: opentlc-mgr
silent: false

common_password: MTI1Mjkx
code_red_breach_challenge_sonarqube_namespace: sonarqube
code_red_breach_challenge_sonarqube_inform_only_policies:
- Fixable Severity at least Important