---
code_red_breach_challenge_argo_customize_num_users: "{{ num_users | default(3) }}"
code_red_breach_challenge_argo_customize_gitea_namespace: gitea
code_red_breach_challenge_argo_customize_argo_namespace: openshift-gitops
code_red_breach_challenge_argo_customize_gitea_admin_user: gitea
code_red_breach_challenge_argo_customize_gitea_admin_password: r3dh4t!
code_red_breach_challenge_argo_customize_gitea_user_name_base: user
code_red_breach_challenge_argo_customize_gitea_user_password: "{{ common_password }}"
code_red_breach_challenge_argo_customize_argo_user_name_base: user
code_red_breach_challenge_argo_customize_argo_user_password: "{{ common_password }}"
code_red_breach_challenge_argo_customize_stackrox_namespace: stackrox
code_red_breach_challenge_argo_customize_stackrox_admin_user: gitea
code_red_breach_challenge_argo_customize_stackrox_admin_password: "{{ common_password }}"
code_red_breach_challenge_argo_customize_pipeline_chunk_size: 5