---
- name: Running Workload Tasks
  ansible.builtin.include_tasks: ./workload.yml
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload removal Tasks
  ansible.builtin.include_tasks: ./remove_workload.yml
  when: ACTION == "destroy" or ACTION == "remove"
