---
galaxy_info:
  role_name: code_red_breach_challenge_big_demo
  author: Wolfgang Kulhanek
  description: |
    Set up the Big Demo environment
  license: MIT
  min_ansible_version: 2.9
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
